sudo: false
language: rust

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      osx_image: xcode8.2
    - os: linux
      dist: trusty

rust:
  - stable
  - beta
  - nightly

script: sh .travis.sh
