[package]
name = "dinghy"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
mobiledevice-sys = { path = "mobiledevice-sys" }
core-foundation = "*"
core-foundation-sys = "*"
error-chain = "*"
libc="*"
tempfile = "*"
tempdir = "0.3"
log="*"
env_logger="*"
clap = "*"
cargo = "*"
