[package]
name = "dinghy"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <mathieu.poumeyol@snips.ai>"]
license = ""
description = "Painless tests on mobile devices"
keywords = [
    "tests", "mobile", "ios", "android"
]

[dependencies]
mobiledevice-sys = { path = "mobiledevice-sys", version = "0.1"}
core-foundation = "*"
core-foundation-sys = "*"
error-chain = "*"
libc="*"
tempfile = "*"
tempdir = "0.3"
log="*"
env_logger="*"
clap = "*"
cargo = "*"
plist = "*"
regex = "*"
